# environment variables
environment:
  nodejs_version: "5"

# scripts that run after cloning repository
install:
  # install DNX
  - dnvm upgrade
  - dotnet restore
  # install node 
  - ps: Install-Product node $Env:nodejs_version
  - npm install -g npm
  - npm install -g webpack  
  
# scripts to run before build
before_build:
  # install node modules
  - cd %APPVEYOR_BUILD_FOLDER%
  - cd Samples.Front
  - npm install
  - npm run postinstall
  - npm run build
  - dotnet build
    
build: off
  
artifacts:
  # put whole folder into a zip file
  - path: Samples.Front\wwwroot
