# environment variables
environment:
  nodejs_version: "5"

# scripts that run after cloning repository
install:
  # install DNX
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - dnvm upgrade
  # install node 
  - ps: Install-Product node $Env:nodejs_version
  - npm install -g npm
  - npm install -g webpack  
  
# scripts to run before build
before_build:
  # install node modules
  - cd %APPVEYOR_BUILD_FOLDER%
  - cd Samples.Front
  - dnu restore
  - npm install
  - npm run postinstall
  # run webpack with production flag
  - npm run build
  # back to original folder
  - cd %APPVEYOR_BUILD_FOLDER%
    
artifacts:
  # put whole folder into a zip file
  - path: Samples.Front\wwwroot
